"""empty message

Revision ID: ee7a29cff89d
Revises: ae4b5a2264d6
Create Date: 2023-05-08 14:29:12.794691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7a29cff89d'
down_revision = 'ae4b5a2264d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Planets_moon_id_fkey', 'Planets', type_='foreignkey')
    op.drop_column('Planets', 'moon_id')
    op.add_column('moon', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'moon', 'Planets', ['planet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moon', type_='foreignkey')
    op.drop_column('moon', 'planet_id')
    op.add_column('Planets', sa.Column('moon_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Planets_moon_id_fkey', 'Planets', 'moon', ['moon_id'], ['id'])
    # ### end Alembic commands ###
